# Generated by Django 3.2 on 2021-05-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcoWeb', '0003_auto_20210520_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modul',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
