# Generated by Django 3.2 on 2021-06-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcoWeb', '0004_auto_20210520_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'ordering': ('judul',)},
        ),
    ]
