# Generated by Django 3.2 on 2021-06-17 13:27

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('telcoWeb', '0005_alter_informations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
