# Generated by Django 3.2 on 2021-06-17 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telcoWeb', '0006_informations_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='informations',
            options={'ordering': ('kategori', 'materi', 'judul')},
        ),
        migrations.RenameField(
            model_name='informations',
            old_name='isi',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='informations',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informations',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telcoWeb.kategori'),
        ),
        migrations.AddField(
            model_name='informations',
            name='materi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telcoWeb.materi'),
        ),
    ]
