# Generated by Django 3.2 on 2021-06-19 06:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('telcoWeb', '0007_auto_20210617_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('modul', 'title'),
            },
        ),
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Modul',
        ),
        migrations.RenameModel(
            old_name='Materi',
            new_name='Type',
        ),
        migrations.DeleteModel(
            name='Informations',
        ),
        migrations.AddField(
            model_name='information',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telcoWeb.type'),
        ),
        migrations.AddField(
            model_name='information',
            name='modul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telcoWeb.modul'),
        ),
    ]
