# Generated by Django 3.2 on 2021-06-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telcoWeb', '0008_auto_20210619_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ('Modul', 'Title')},
        ),
        migrations.RenameField(
            model_name='information',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='created',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='modul',
            new_name='Modul',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='updated',
            new_name='Updated',
        ),
        migrations.RenameField(
            model_name='modul',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='information',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telcoWeb.category'),
        ),
    ]
